### ISSUE TITLE
On clickthrough action, we're missing hypeAdExit reference

### ISSUE THREAD

**Issue by francoisbussery** [tumult/hype-export-scripts#1]
When running in preview a timeline with a clickthrough action, I have in the console the following issue:
Error in hypeAdExit: ReferenceError: hypeAdExit is not defined

Can you confirm that the package works with non professional version?
My Hype version is 3.6.3 (584) Standard Edition

**Comment by jmfd** [comment]
Export Scripts do not work with the Standard version of Hype; it looks like a bug that the actions show up at all.

In the Professional Version, you would get an item in the Preview menu to preview using a specific export script as well as export menu items.
