### ISSUE TITLE
exitAPI() for Adwords needed

### ISSUE THREAD

**Issue by Vaeshkar** [tumult/hype-export-scripts#3]
Follow message received when testing my Hype creatives: 
_Your click was successful and should track correctly
Warning: This creative is not using the ExitApi. The Google-hosted ExitApi is required to make a select area of the creative clickable. Without the ExitApi, a click on any portion of the creative will click through to the landing page set in AdWords. If this is intended, please note your click was successful and should track correctly._

[Source](https://support.google.com/adwords/answer/6335679?authuser=0&hl=en)

**Comment by Vaeshkar** [comment]
[300x600_hsdt_srgb_GDN.zip](https://github.com/tumult/hype-export-scripts/files/1987880/300x600_hsdt_srgb_GDN.zip)
[970x250_hsdt_srgb_GDN.zip](https://github.com/tumult/hype-export-scripts/files/1987881/970x250_hsdt_srgb_GDN.zip)
[160x600_hsdt_srgb_GDN.zip](https://github.com/tumult/hype-export-scripts/files/1987882/160x600_hsdt_srgb_GDN.zip)




Test files added, guys.

**Comment by jmfd** [comment]
Thanks - I think ultimately Adwords will need its own Export Script since it is different than DCM.

@themorgantown made a version that we're testing here, but it isn't official yet. Feel free to try it out:

https://gist.github.com/themorgantown/766d6709793e2c2d88e65a0cd502cfa1

**Comment by themorgantown** [comment]
See https://tumult.com/hype/export-scripts/ for the AdWords export script
